### PR TITLE
Add caveat on results pages

### PR DESCRIPTION
**Pull request by jeffcarp**
Via discussion in #107.

See it here: https://caveat-dot-wptdashboard.appspot.com

### CODE REVIEW

**Comment by rwaldron** [comment]
👍

**Comment by jgraham** [comment]
I don't know what "reliable view of web-platform features" means. In particular "view" in that sentence is hard to interpret. I assume you mean something like "Data is […] not a useful metric for [evaluating feature completeness|comparing browsers|assessing overall quality]"

**Comment by jeffcarp** [comment]
@jgraham I was hoping "view" would be general enough e.g. to cover the use cases you listed, but I can make the wording more precise.

Since there hasn't been any other feedback on this today I'm going to land it (after tweaking the language as mentioned above).

**Comment by jgraham** [comment]
Thanks, I think that wording is a big improvement.

**Pull request merged**
